#!/bin/bash

# Test Square Reward Processing
# This script tests the Bitcoin Rewards plugin with detailed rate fetch logging

echo "=========================================="
echo "Bitcoin Rewards - Square Test"
echo "=========================================="
echo ""

# Configuration
STORE_ID="${STORE_ID:-DWJ4gyqwVYkSQBgDD7py2DW5izoNnCD9PBbK7P332hW8}"
BTCPAY_URL="${BTCPAY_URL:-http://localhost:81}"
AMOUNT="${AMOUNT:-10.00}"
CURRENCY="${CURRENCY:-CAD}"

echo "Configuration:"
echo "  Store ID: $STORE_ID"
echo "  BTCPay URL: $BTCPAY_URL"
echo "  Test Amount: $AMOUNT $CURRENCY"
echo ""

# Test endpoint
TEST_URL="${BTCPAY_URL}/plugins/bitcoin-rewards/${STORE_ID}/test/square?amount=${AMOUNT}&currency=${CURRENCY}"

echo "Test URL: $TEST_URL"
echo ""
echo "=========================================="
echo "Step 1: Check if test API is accessible"
echo "=========================================="

PING_URL="${BTCPAY_URL}/plugins/bitcoin-rewards/${STORE_ID}/test/ping"
echo "GET $PING_URL"
echo ""

curl -s "$PING_URL" | jq . 2>/dev/null || echo "⚠️  Need to authenticate via browser first"
echo ""

echo "=========================================="
echo "Step 2: Trigger test reward"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT: You must be logged into BTCPay in your browser!"
echo ""
echo "Run this command in your browser console or use Postman/curl with session cookie:"
echo ""
echo "fetch('$TEST_URL', { method: 'POST', credentials: 'include' })"
echo "  .then(r => r.json())"
echo "  .then(d => console.log(d))"
echo ""
echo "=========================================="
echo "Step 3: Monitor logs"
echo "=========================================="
echo ""
echo "Run this in another terminal:"
echo ""
echo "docker logs -f generated_btcpayserver_1 | grep '\[RATE FETCH\]'"
echo ""
echo "You should see:"
echo "  [RATE FETCH] Store XXX: Fetching BTC_CAD"
echo "  [RATE FETCH] Primary rules: ..."
echo "  [RATE FETCH] ✅ SUCCESS: BTC_CAD = 95234.56"
echo ""
echo "Or if failing:"
echo "  [RATE FETCH] ❌ FAILED for BTC_CAD"
echo "  [RATE FETCH] Errors: RateUnavailable"
echo ""
echo "=========================================="
echo "Alternative: Use curl with cookie"
echo "=========================================="
echo ""
echo "1. Login to BTCPay in browser"
echo "2. Open Developer Tools → Network tab"
echo "3. Find the 'Cookie' header value"
echo "4. Run:"
echo ""
echo "curl -X POST '$TEST_URL' \\"
echo "  -H 'Cookie: YOUR_COOKIE_HERE'"
echo ""
