#nullable enable
// <auto-generated />
using System;
using BTCPayServer.Plugins.BitcoinRewards.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BTCPayServer.Plugins.BitcoinRewards.Data.Migrations
{
    [DbContext(typeof(BitcoinRewardsPluginDbContext))]
    [Migration("20260222000000_AddDualBalance")]
    partial class AddDualBalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("BTCPayServer.Plugins.BitcoinRewards");
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
            modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BTCPayServer.Plugins.BitcoinRewards.Data.BitcoinRewardRecord", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("ClaimLink").HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<DateTime?>("ClaimedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                b.Property<string>("CustomerEmail").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<string>("CustomerPhone").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<DateTime?>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ErrorMessage").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("OrderId").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<DateTime?>("PaidAt").HasColumnType("timestamp with time zone");
                b.Property<string>("PayoutId").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PayoutMethod").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PayoutProcessor").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<int>("Platform").HasColumnType("integer");
                b.Property<string>("PullPaymentId").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime?>("RedeemedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("RetryCount").HasColumnType("integer");
                b.Property<decimal>("RewardAmount").HasColumnType("numeric(18,8)");
                b.Property<long>("RewardAmountSatoshis").HasColumnType("bigint");
                b.Property<DateTime?>("SentAt").HasColumnType("timestamp with time zone");
                b.Property<string>("StoreId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<int>("Status").HasColumnType("integer");
                b.Property<decimal>("TransactionAmount").HasColumnType("numeric(18,8)");
                b.Property<string>("TransactionId").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.HasKey("Id");
                b.HasIndex("StoreId");
                b.HasIndex("Status");
                b.HasIndex("StoreId", "TransactionId", "Platform");
                b.ToTable("BitcoinRewardRecords", "BTCPayServer.Plugins.BitcoinRewards");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.BitcoinRewards.Data.BoltCardLink", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("StoreId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("PullPaymentId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("CardUid").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("BoltcardId").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<long>("TotalRewardedSatoshis").HasDefaultValue(0L).HasColumnType("bigint");
                b.Property<DateTime?>("LastRewardedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("StoreId");
                b.HasIndex("PullPaymentId");
                b.HasIndex("BoltcardId");
                b.HasIndex(new[] { "StoreId", "PullPaymentId" }).IsUnique().HasDatabaseName("IX_BoltCardLinks_StoreId_PullPaymentId_Unique");
                b.ToTable("BoltCardLinks", "BTCPayServer.Plugins.BitcoinRewards");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.BitcoinRewards.Data.CustomerWallet", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("StoreId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("PullPaymentId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("CardUid").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("BoltcardId").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<long>("CadBalanceCents").HasDefaultValue(0L).HasColumnType("bigint");
                b.Property<bool>("AutoConvertToCad").HasDefaultValue(true).HasColumnType("boolean");
                b.Property<long>("TotalRewardedSatoshis").HasDefaultValue(0L).HasColumnType("bigint");
                b.Property<long>("TotalRewardedCadCents").HasDefaultValue(0L).HasColumnType("bigint");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("LastRewardedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ApiTokenHash").HasMaxLength(128).HasColumnType("character varying(128)");
                b.HasKey("Id");
                b.HasIndex("StoreId");
                b.HasIndex("PullPaymentId");
                b.HasIndex("BoltcardId");
                b.HasIndex("CardUid");
                b.HasIndex("ApiTokenHash");
                b.HasIndex(new[] { "StoreId", "PullPaymentId" }).IsUnique().HasDatabaseName("IX_CustomerWallets_StoreId_PullPaymentId_Unique");
                b.ToTable("CustomerWallets", "BTCPayServer.Plugins.BitcoinRewards");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.BitcoinRewards.Data.WalletTransaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("CustomerWalletId").HasColumnType("uuid");
                b.Property<int>("Type").HasColumnType("integer");
                b.Property<long>("SatsAmount").HasDefaultValue(0L).HasColumnType("bigint");
                b.Property<long>("CadCentsAmount").HasDefaultValue(0L).HasColumnType("bigint");
                b.Property<decimal>("ExchangeRate").HasColumnType("numeric");
                b.Property<string>("Reference").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("CustomerWalletId");
                b.HasIndex("CreatedAt");
                b.ToTable("WalletTransactions", "BTCPayServer.Plugins.BitcoinRewards");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.BitcoinRewards.Data.WalletTransaction", b =>
            {
                b.HasOne("BTCPayServer.Plugins.BitcoinRewards.Data.CustomerWallet", null)
                    .WithMany()
                    .HasForeignKey("CustomerWalletId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
        }
    }
}
