#nullable enable
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace BTCPayServer.Plugins.BitcoinRewards.Data.Migrations
{
    [DbContext(typeof(BitcoinRewardsPluginDbContext))]
    partial class BitcoinRewardsPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("BTCPayServer.Plugins.BitcoinRewards");
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
            modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BTCPayServer.Plugins.BitcoinRewards.Data.BitcoinRewardRecord", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("ClaimLink").HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<DateTime?>("ClaimedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                b.Property<string>("CustomerEmail").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<string>("CustomerPhone").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<DateTime?>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ErrorMessage").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("OrderId").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<DateTime?>("PaidAt").HasColumnType("timestamp with time zone");
                b.Property<string>("PayoutId").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PayoutMethod").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PayoutProcessor").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<int>("Platform").HasColumnType("integer");
                b.Property<string>("PullPaymentId").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime?>("RedeemedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("RetryCount").HasColumnType("integer");
                b.Property<decimal>("RewardAmount").HasColumnType("numeric(18,8)");
                b.Property<long>("RewardAmountSatoshis").HasColumnType("bigint");
                b.Property<DateTime?>("SentAt").HasColumnType("timestamp with time zone");
                b.Property<string>("StoreId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<int>("Status").HasColumnType("integer");
                b.Property<decimal>("TransactionAmount").HasColumnType("numeric(18,8)");
                b.Property<string>("TransactionId").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");

                b.HasKey("Id");
                b.HasIndex("StoreId");
                b.HasIndex("Status");
                b.HasIndex("StoreId", "TransactionId", "Platform");
                b.ToTable("BitcoinRewardRecords", "BTCPayServer.Plugins.BitcoinRewards");
            });
        }
    }
}

